import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import app from '../../app.json';
import styleRegistry from '../../style-registry.json';
import './style.css';
import './style-gallery.css';

type Style=string;
type Card={title:string;subtitle:string;tags:string[];style:Style};
type Asset={id:string;position:number;rotation:0|90|180|270;crop:number[];confirmed?:{date:string;place:string;source:string};inspection?:{text:string;candidate_dates:string[];warning:string;vision_text?:string}};
type Detail={id:string;date:string;place:string;rotation:0|90|180|270;crop:number[]};
type Album={title:string;subtitle:string;pages:{asset_ids:string[];caption:string;caption_kind:'creative'|'excerpt'}[]};
type Version={id:string;content:Card&Album;files:string[];created:number};
type Task={id:string;status:string;error?:string;kind:string;result?:{questions?:string[]}};
type Work={id:string;title:string;input:{memory?:string;states?:string[]};versions:Version[];assets:Asset[];task:Task|null};
type Session={user_id:string;preference:Style|null;used:number;limit:number};
type Health={model_ready:boolean;ocr_enabled:boolean;invite_ready:boolean};
const isCard=app.kind==='card';
const styleEntries=styleRegistry.styles;
const styleNames:Record<string,string>=Object.fromEntries(styleEntries.map(s=>[s.id,s.name]));
const styleMarks=['Aa','✳','a.','№','✎','⌁','○','01'];
const INVITE_KEY='studio-remembered-invite';
const assetUrl=(wid:string,aid:string)=>`/api/works/${wid}/assets/${aid}`;
const fileUrl=(wid:string,vid:string,name:string)=>`/api/works/${wid}/versions/${vid}/${name}`;
async function api<T=any>(path:string,method='GET',body?:unknown):Promise<T>{
 const form=body instanceof FormData;
 const res=await fetch('/api'+path,{method,headers:{'X-Requested-With':'studio',...(!form&&body?{'Content-Type':'application/json'}:{})},body:body?(form?body:JSON.stringify(body)):undefined});
 const data=await res.json();
 if(!res.ok)throw new Error(typeof data.detail==='string'?data.detail:res.status===422?'请检查输入长度、格式与必填信息。':'请求失败，请重试。');
 return data;
}
function Icon({name='spark',size=20}:{name?:string;size?:number}){
 const paths:Record<string,React.ReactNode>={spark:<><path d="m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6Z"/><path d="m20 2 1 3 3 1"/></>,arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,download:<><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></>,plus:<path d="M12 4v16M4 12h16"/>,book:<><path d="M4 4h7l2 2h7v15h-7l-2-2H4zM11 4v15"/></>,check:<path d="m5 12 4 4L19 6"/>,image:<><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1"/><path d="m3 17 6-5 4 3 3-6 5 8"/></>};
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.spark}</svg>;
}
function CropPreview({src,detail}:{src:string;detail:Detail}){
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{let dead=false;const im=new Image();im.onload=()=>{if(dead||!canvas.current)return;const temp=document.createElement('canvas');const swap=detail.rotation%180!==0;temp.width=swap?im.height:im.width;temp.height=swap?im.width:im.height;const ctx=temp.getContext('2d')!;ctx.translate(temp.width/2,temp.height/2);ctx.rotate(detail.rotation*Math.PI/180);ctx.drawImage(im,-im.width/2,-im.height/2);const [x,y,w,h]=detail.crop;const target=canvas.current;target.width=480;target.height=Math.round(480*h*temp.height/(w*temp.width));target.getContext('2d')!.drawImage(temp,x*temp.width,y*temp.height,w*temp.width,h*temp.height,0,0,target.width,target.height);};im.src=src;return()=>{dead=true;};},[src,detail.rotation,detail.crop.join(',')]);
 return <canvas ref={canvas} className="crop-preview" aria-label="裁剪后的素材预览"/>;
}
function App(){
 const [health,setHealth]=useState<Health|null>(null),[session,setSession]=useState<Session|null>(null),[invite,setInvite]=useState('');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState<'create'|'library'>('create');
 const [states,setStates]=useState(['困','想出门','不想社交']),[memory,setMemory]=useState(''),[style,setStyle]=useState<Style>('magazine');
 const [work,setWork]=useState<Work|null>(null),[library,setLibrary]=useState<{id:string;title:string;created:number}[]>([]),[versionId,setVersionId]=useState('');
 const [feedback,setFeedback]=useState(''),[card,setCard]=useState<Card|null>(null),[album,setAlbum]=useState<Album|null>(null),[details,setDetails]=useState<Detail[]>([]);
 const [files,setFiles]=useState<File[]>([]),[cloud,setCloud]=useState(false),[deleteArmed,setDeleteArmed]=useState(false),[lightbox,setLightbox]=useState('');
 const version=work?.versions.find(v=>v.id===versionId)||work?.versions[0];
 const running=work?.task&&['queued','running'].includes(work.task.status);
 const pending=busy||!!running;
 const cleanStates=states.map(s=>s.trim());
 const stateError=cleanStates.some(s=>!s)?'请填满三个今日状态。':cleanStates.some(s=>s.length>20)?'每个状态最多 20 个字。':'';
 const workRef=useRef<string|null>(null),previewRef=useRef<HTMLElement>(null),focusPreview=useRef(false);
 useEffect(()=>{workRef.current=work?.id||null;},[work?.id]);
 async function refreshSession(){const s=await api<Session>('/session');setSession(s);return s;}
 async function refreshLibrary(){setLibrary(await api('/works'));}
 async function openWork(id:string){const next=await api<Work>('/works/'+id);setWork(next);setVersionId('');setTab('create');setDeleteArmed(false);}
 async function act(fn:()=>Promise<void>){setError('');setNotice('');setBusy(true);try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{api<Health>('/health').then(setHealth).catch(()=>setError('服务暂时无法连接，请检查启动状态。'));(async()=>{let s:Session;try{s=await api<Session>('/session');}catch{return;}const remembered=localStorage.getItem(INVITE_KEY);if(remembered){try{await api('/session','POST',{invite:remembered});s=await refreshSession();}catch(e){if((e as Error).message.includes('有效期'))localStorage.removeItem(INVITE_KEY);}}setSession(s);if(s.preference)setStyle(s.preference);await refreshLibrary();})();},[]);
 useEffect(()=>{if(!running||!work)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;const id=work.id;const tick=async()=>{try{const next=await api<Work>('/works/'+id);if(cancelled||workRef.current!==id)return;setWork(next);if(['queued','running'].includes(next.task?.status||''))timer=setTimeout(tick,1500);else{await refreshLibrary();await refreshSession();}}catch(e){if(!cancelled){setError((e as Error).message);timer=setTimeout(tick,3000);}}};timer=setTimeout(tick,800);return()=>{cancelled=true;clearTimeout(timer);};},[work?.id,!!running]);
 useEffect(()=>{if(!work)return;setMemory(work.input.memory||'');if(work.input.states)setStates(work.input.states);setDetails(work.assets.map(a=>({id:a.id,date:a.confirmed?.date||'',place:a.confirmed?.place||'',rotation:a.rotation,crop:a.crop})));},[work?.id,work?.task?.status]);
 useEffect(()=>{if(!version){setCard(null);setAlbum(null);return;}setCard(version.content);setAlbum(version.content);if(version.content.style)setStyle(version.content.style);},[version?.id]);
 useEffect(()=>{if(version&&focusPreview.current){focusPreview.current=false;previewRef.current?.scrollIntoView({behavior:'smooth',block:'start'});}},[version?.id]);
 useEffect(()=>{if(!lightbox)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setLightbox('');};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[lightbox]);
 async function accepted(result:{work_id:string;task_id:string}){focusPreview.current=true;await openWork(result.work_id);await refreshLibrary();await refreshSession();}
 function requireSession(){if(!session)throw new Error('请先在上方输入邀请口令，开始你的私人创作。');}
 async function create(){requireSession();if(isCard){if(stateError)throw new Error(stateError);await accepted(await api('/cards','POST',{states:cleanStates,memory,style}));}else{if(!files.length)throw new Error('先选几张票根或照片吧。');const form=new FormData();files.forEach(f=>form.append('files',f));form.append('memory',memory);form.append('cloud_vision',String(cloud));const result=await api('/albums','POST',form);await accepted(result);setFiles([]);if(result.duplicates)setNotice(`已合并 ${result.duplicates} 张重复素材。`);}}
 function fresh(){setWork(null);setVersionId('');setCard(null);setAlbum(null);setMemory('');setFeedback('');setFiles([]);setDetails([]);setError('');setNotice('');setTab('create');setDeleteArmed(false);}
 function chooseFiles(list:FileList|null){if(!list)return;const chosen=[...files,...Array.from(list)];if(chosen.length>10){setError('一次最多选择 10 张素材。');return;}if(chosen.some(f=>f.size>20_000_000||!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('支持 JPEG、PNG、WebP，单张最多 20MB。');return;}setFiles(chosen);setError('');}
 function patchDetail(id:string,patch:Partial<Detail>){setDetails(ds=>ds.map(d=>d.id===id?{...d,...patch}:d));}
 function move(index:number,delta:number){const next=[...details];[next[index],next[index+delta]]=[next[index+delta],next[index]];setDetails(next);}
 const login=<form className="invite" onSubmit={e=>{e.preventDefault();act(async()=>{await api('/session','POST',{invite});localStorage.setItem(INVITE_KEY,invite);const s=await refreshSession();if(s.preference)setStyle(s.preference);await refreshLibrary();setInvite('');});}}><div><strong>一份小范围的创作邀请</strong><span>输入口令，开启只属于你的工作台</span></div><div className="invite-input"><input aria-label="邀请口令" type="password" autoComplete="off" placeholder="邀请口令" value={invite} onChange={e=>setInvite(e.target.value)} required maxLength={200}/><button disabled={busy} type="submit">进入 <Icon name="arrow" size={16}/></button></div></form>;
 return <div className={isCard?'app card-app':'app album-app'}>
  <header className="header"><button className="brand" onClick={fresh}><span className="brand-mark"><Icon name={isCard?'spark':'book'} size={24}/></span><span>{app.name}<small>{isCard?'A PORTRAIT OF NOW':'THE LITTLE ARCHIVE'}</small></span></button><nav><button className={tab==='create'?'active':''} onClick={()=>setTab('create')}>创作台</button><button className={tab==='library'?'active':''} onClick={()=>{setTab('library');if(session)act(refreshLibrary);}}>我的作品 <span>{library.length.toString().padStart(2,'0')}</span></button></nav><div className="session-actions"><span className="private"><span className="dot"/> 私人创作空间</span>{session&&<button className="logout-button" disabled={busy} onClick={()=>act(async()=>{await api('/session','DELETE');localStorage.removeItem(INVITE_KEY);fresh();setLibrary([]);setSession(null);setNotice('已退出当前工作台。');})}>退出</button>}</div></header>
  <main>
   <section className="intro"><div><div className="eyebrow">{isCard?'MEET YOURSELF, JUST FOR TODAY.':'SOME DAYS DESERVE A PAPER TRAIL.'}</div><h1>{isCard?<>把今天的你，<em>印成封面。</em></>:<>把来过的日子，<em>好好留下。</em></>}</h1><p>{isCard?'三个状态，一点灵感。让创意编辑为此刻的你，做一张限时发行的人格卡。':'车票、展览票、随手拍下的照片。让回忆整理员，把零散的瞬间装订成册。'}</p></div><div className="intro-note">{isCard?'不是人格测评\n是今天的小小自画像':'一张票根，一次在场。\n一段回忆，慢慢收藏。'}<span>✳</span></div></section>
   {!session&&login}
   {(error||notice)&&<div className={error?'message error':'message'} role={error?'alert':'status'}>{error||notice}<button aria-label="关闭提示" onClick={()=>{setError('');setNotice('');}}>×</button></div>}
   {tab==='library'?<section className="library"><div className="section-heading"><h2>我的小小收藏</h2><button className="text-button" onClick={fresh}><Icon name="plus"/> 新建作品</button></div>{library.length?<div className="library-grid">{library.map((w,i)=><button className="library-item" key={w.id} onClick={()=>act(()=>openWork(w.id))}><span className="library-number">{String(i+1).padStart(2,'0')}</span><h3>{w.title}</h3><span>{new Date(w.created*1000).toLocaleDateString('zh-CN')} <Icon name="arrow"/></span></button>)}</div>:<div className="empty"><Icon name="book" size={44}/><h3>第一份作品，还在等你。</h3><p>生成的每一版都会留在这里。</p><button className="primary" onClick={fresh}>开始创作 <Icon name="arrow"/></button></div>}</section>:
   <div className="workspace"><section className={isCard?'editor card-editor':'editor'}><div className="section-heading"><span className="step">01 / {isCard?'给今天一点线索':'收集这一天'}</span>{work&&<button className="text-button" onClick={fresh}>另起一份 <Icon name="plus" size={15}/></button>}</div>
    {isCard?<><label className="field-label">今天，你是什么状态？<span>恰好三个</span></label><div className="state-inputs">{states.map((s,i)=><div key={i}><span>0{i+1}</span><input aria-label={`状态 ${i+1}`} maxLength={20} value={s} disabled={!!work} onChange={e=>setStates(states.map((v,j)=>i===j?e.target.value:v))}/></div>)}</div>{stateError&&<p className="field-error" role="alert">{stateError}</p>}<div className="suggestions"><span>找点灵感</span>{['想躺平','有点期待','灵感过载'].map((s,i)=><button key={s} disabled={!!work} onClick={()=>setStates(states.map((v,j)=>i===j?s:v))}>+ {s}</button>)}</div></>:
    !work?<><label className="upload" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();chooseFiles(e.dataTransfer.files);}}><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{chooseFiles(e.target.files);e.target.value='';}}/><span className="upload-icon"><Icon name="image" size={32}/></span><strong>放进几张票根，或照片</strong><span>点击选择，也可以拖到这里</span><small>1–10 张 · JPG / PNG / WebP · 单张 ≤ 20MB</small></label>{files.length>0&&<div className="file-list">{files.map((f,i)=><div key={i}><Icon name="image" size={16}/><span>{f.name}</span><button aria-label={`移除 ${f.name}`} onClick={()=>setFiles(files.filter((_,j)=>i!==j))}>×</button></div>)}</div>}</>:<div className="asset-summary"><Icon name="book" size={32}/><div><strong>{work.assets.length} 份时光碎片</strong><p>核对信息，再交给整理员编排。</p></div></div>}
    {isCard?<details className="memory-control" open={!!memory&&!work}><summary>补充今天发生了什么 <span>选填</span></summary><label className="field-label" htmlFor="memory">给这一版一点背景</label><textarea id="memory" value={memory} disabled={!!work} onChange={e=>setMemory(e.target.value)} maxLength={500} rows={3} placeholder="比如：坐了三站地铁，只为买一杯咖啡。"/><div className="field-foot">小事也值得做封面。<span>{memory.length}/500</span></div></details>:<><label className="field-label" htmlFor="memory">给这一天留一句话<span>选填</span></label><textarea id="memory" value={memory} onChange={e=>setMemory(e.target.value)} maxLength={1000} rows={3} placeholder="比如：终于去了那场惦记很久的展览。"/><div className="field-foot">不记得的细节，可以先留白。<span>{memory.length}/1000</span></div></>}
    {isCard&&<><label className="field-label">选一种表达方式 <span>{styleEntries.length} 款预设 · 可记住常用风格</span></label><div className="style-grid">{styleEntries.map((entry,i)=><button key={entry.id} className={`style-choice ${style===entry.id?'selected':''}`} onClick={()=>setStyle(entry.id)} aria-pressed={style===entry.id} title={entry.description}><span className={`style-swatch swatch-${entry.id}`}><span>{styleMarks[i]}</span><i/><b/></span><span>{entry.name} {style===entry.id&&<Icon name="check" size={14}/>}</span></button>)}</div><p className="style-description">{styleEntries.find(entry=>entry.id===style)?.description}</p><div className="preference"><button className="text-button" disabled={!session||busy} onClick={()=>act(async()=>{await api('/preferences','PUT',{style});await refreshSession();setNotice('已保存风格偏好，下次创作时使用。');})}>{session?.preference===style?'✓ 已记住这个风格':'记住这个风格'}</button>{session?.preference&&<button className="text-button muted" onClick={()=>act(async()=>{await api('/preferences','DELETE');await refreshSession();setNotice('风格偏好已清除。');})}>清除偏好</button>}</div></>}
    {!isCard&&!work&&<label className="checkline"><input type="checkbox" checked={cloud} onChange={e=>setCloud(e.target.checked)}/><span>允许这次使用云端图片理解<small>默认只在本地或应用服务器识别。选中后，图片会发送给已配置的模型服务。</small></span></label>}
    {!work&&<><button className="primary full mobile-submit" disabled={pending||(isCard&&(!health?.model_ready||!!stateError))} onClick={()=>act(create)}><Icon name={isCard?'spark':'book'}/>{busy?'正在提交…':isCard?'生成今日人格卡':'开始整理回忆'}<Icon name="arrow"/></button><p className="privacy-note">{isCard?'只记录此刻，不给你贴长期标签。':'照片与票根默认私有，分享从下载开始。'}</p></>}
    {!health?.model_ready&&<div className="service-note"><span className="dot"/><div><strong>创作模型暂未连接</strong><p>{version?'已有作品仍可直接修改文案并下载。连接模型后可使用 AI 改稿。':isCard?'连接模型后，即可开始生成和改稿。右侧为排版示例。':'你可以上传并核对素材；连接模型后即可自动编排成册。'}</p></div></div>}
    {work&&<><div className="task-status" role="status"><span className={running?'spinner':'dot'}/><div><strong>{running?(work.task?.kind==='inspect'?'正在检查素材…':'编辑正在创作…'):work.task?.status==='failed'?'这次处理没能完成':work.task?.status==='awaiting_details'?'有一些细节，想和你核对':version?'作品已存入你的收藏':'等待下一步'}</strong><p>{running?'可以稍后回来，处理进度会保留。':work.task?.error|| (version?'预览即导出，保存的是同一张图片。':'不确定的内容可以留白继续。')}</p></div></div>{work.task?.status==='failed'&&<button className="secondary full" disabled={pending} onClick={()=>act(async()=>accepted(await api(`/tasks/${work.task!.id}/retry`,'POST')))}>重试本次任务</button>}
    {version&&<><label className="field-label" htmlFor="feedback">再让编辑改一改</label><textarea id="feedback" value={feedback} onChange={e=>setFeedback(e.target.value)} maxLength={500} rows={2} placeholder={isCard?'少点鸡汤，再冷幽默一点。':'旁白再简短一点，多留些空白。'}/>{isCard&&card&&card.style!==style&&<p className="style-change-hint">已选“{styleNames[style]}”；不填写改稿说明也可直接重新排版。</p>}<button className="primary full revision-action mobile-submit" disabled={pending||!health?.model_ready||(!feedback.trim()&&(!isCard||!card||card.style===style))} onClick={()=>act(async()=>{if(isCard&&card&&card.style!==style&&!feedback.trim())await accepted(await api(`/works/${work.id}/card-content`,'POST',{...card,style}));else{await accepted(await api(`/works/${work.id}/revise`,'POST',{feedback,base_version_id:version.id,...(isCard?{style}:{})}));setFeedback('');}})}><span>按我的想法改稿</span><Icon name="arrow"/></button></>}
    <button className="delete-button" disabled={pending} onClick={()=>{if(!deleteArmed){setDeleteArmed(true);return;}act(async()=>{await api('/works/'+work.id,'DELETE');fresh();await refreshLibrary();setNotice('作品及关联素材、版本已删除。');});}}>{deleteArmed?'确认删除这份作品及全部素材':'删除这份作品'}</button>{deleteArmed&&<button className="text-button" onClick={()=>setDeleteArmed(false)}>取消</button>}</>}
   </section>
   <section className="preview-area" ref={previewRef}><div className="section-heading"><span className="step">02 / {work?.assets.length&&!version&&!isCard?'核对时光碎片':'看看这一版'}</span><span className="preview-label">{version?'1080 × 1440 · PNG':'排版示例 · 非生成结果'}</span></div>
    {!isCard&&work&&work.assets.length>0&&<details className="review-panel" open={!version}><summary>{version?'核对、裁剪与调整素材顺序':'先核对一下，让回忆更准确。'} <span>{details.length} 张素材</span></summary>{work.task?.result?.questions?.map((q,i)=><p key={i} className="question">{q}</p>)}<div className="review-list">{details.map((d,i)=>{const a=work.assets.find(a=>a.id===d.id)!;return <article className="review-item" key={d.id}><div className="review-image"><CropPreview src={assetUrl(work.id,d.id)} detail={d}/><span>0{i+1}</span></div><div className="review-info"><div className="review-top"><strong>碎片 0{i+1}</strong><span><button disabled={pending||i===0} onClick={()=>move(i,-1)} aria-label={`上移碎片 ${i+1}`}>↑</button><button disabled={pending||i===details.length-1} onClick={()=>move(i,1)} aria-label={`下移碎片 ${i+1}`}>↓</button></span></div><p className="ocr-warning">{a.inspection?.warning||'等待识别。所有信息均需你核对。'}</p>{!!a.inspection?.candidate_dates.length&&<p className="candidates">候选日期：{a.inspection.candidate_dates.join(' / ')}（未确认）</p>}<div className="detail-fields"><label>日期<input aria-label={`碎片 ${i+1} 日期`} type="date" value={d.date} disabled={pending} onChange={e=>patchDetail(d.id,{date:e.target.value})}/></label><label>地点<input aria-label={`碎片 ${i+1} 地点`} maxLength={40} value={d.place} disabled={pending} placeholder="不记得就留白" onChange={e=>patchDetail(d.id,{place:e.target.value})}/></label></div><details className="crop-controls"><summary>查看识别文字 / 手动裁剪</summary><p className="ocr-text">{a.inspection?.text||'未识别出可用文字。'}</p>{a.inspection?.vision_text&&<p className="ocr-text">云端理解（待核对）：{a.inspection.vision_text}</p>}<button className="secondary" disabled={pending} onClick={()=>patchDetail(d.id,{rotation:((d.rotation+90)%360) as Detail['rotation']})}>旋转 90°</button><button className="text-button" disabled={pending} onClick={()=>patchDetail(d.id,{crop:[0,0,1,1],rotation:0})}>还原</button>{['左侧','顶部','宽度','高度'].map((label,j)=><label className="crop-range" key={j}>{label}<input type="range" disabled={pending} min={j<2?0:5} max={j<2?Math.round((1-d.crop[j+2])*100):Math.round((1-d.crop[j-2])*100)} step="1" value={Math.round(d.crop[j]*100)} onChange={e=>patchDetail(d.id,{crop:d.crop.map((v,k)=>k===j?Number(e.target.value)/100:v)})}/><span>{Math.round(d.crop[j]*100)}%</span></label>)}</details></div></article>;})}</div><div className="review-actions"><button className="primary" disabled={pending||!health?.model_ready} onClick={()=>act(async()=>accepted(await api(`/works/${work.id}/details`,'POST',{assets:details,memory,skip:false})))}>核对好了，编排成册 <Icon name="arrow"/></button><button className="text-button" disabled={pending||!health?.model_ready} onClick={()=>act(async()=>accepted(await api(`/works/${work.id}/details`,'POST',{assets:details,memory,skip:true})))}>保留空白，跳过补问</button></div></details>}
    {version&&work?<><div className="version-bar"><label>作品版本 <select aria-label="选择作品版本" value={version.id} onChange={e=>setVersionId(e.target.value)}>{work.versions.map((v,i)=><option value={v.id} key={v.id}>第 {work.versions.length-i} 版{!i?' · 最新':''}</option>)}</select></label><a className="download-button" href={fileUrl(work.id,version.id,isCard?'page-01.png':'album.zip')+'?download=true'} download><Icon name="download" size={17}/>{isCard?'下载高清 PNG':'打包下载'}</a></div><div className={isCard?'actual-card':'album-pages'}>{version.files.filter(f=>f.endsWith('.png')).map((f,i)=><figure key={f}><img src={fileUrl(work.id,version.id,f)} alt={`${work.title} ${i===0?'封面':`第 ${i+1} 页`}`} onClick={()=>setLightbox(fileUrl(work.id,version.id,f))}/>{!isCard&&<figcaption><span>{i===0?'封面':`第 ${i+1} 页`}</span><a href={fileUrl(work.id,version.id,f)+'?download=true'} download>下载 PNG ↓</a></figcaption>}</figure>)}</div>
    <details className="manual-edit"><summary>直接修改{isCard?'文案':'小册标题与旁白'} <span>无需调用模型</span></summary>{isCard&&card?<><label>标题<input maxLength={24} value={card.title} onChange={e=>setCard({...card,title:e.target.value})}/></label><label>副标题<textarea maxLength={70} value={card.subtitle} onChange={e=>setCard({...card,subtitle:e.target.value})}/></label><div className="tag-edit">{card.tags.map((t,i)=><input key={i} aria-label={`标签 ${i+1}`} maxLength={12} value={t} onChange={e=>setCard({...card,tags:card.tags.map((v,j)=>i===j?e.target.value:v)})}/>)}</div><button className="secondary" disabled={pending} onClick={()=>act(async()=>accepted(await api(`/works/${work.id}/card-content`,'POST',{...card,style})))}>保存文案与当前风格为新版</button></>:album&&<><label>封面标题<input maxLength={24} value={album.title} onChange={e=>setAlbum({...album,title:e.target.value})}/></label><label>封面副标题<textarea maxLength={70} value={album.subtitle} onChange={e=>setAlbum({...album,subtitle:e.target.value})}/></label>{album.pages.map((p,i)=><label key={i}>第 {i+2} 页旁白<textarea maxLength={90} value={p.caption} onChange={e=>setAlbum({...album,pages:album.pages.map((v,j)=>i===j?{...v,caption:e.target.value,caption_kind:'creative'}:v)})}/></label>)}<button className="secondary" disabled={pending} onClick={()=>act(async()=>{const ids=details.map(d=>d.id);let offset=0;const pages=album.pages.map(p=>{const next={...p,asset_ids:ids.slice(offset,offset+p.asset_ids.length)};offset+=p.asset_ids.length;return next;});await accepted(await api(`/works/${work.id}/album-content`,'POST',{draft:{title:album.title,subtitle:album.subtitle,pages},details:{assets:details,memory,skip:true}}));})}>保存文字、裁剪与排序为新版</button></>}</details></>:
    <div className={`sample-stage ${!isCard?'sample-album':''}`}><div className="sample-note">{isCard?'YOUR EVERYDAY,\nCOVER-WORTHY.':'A LITTLE COLLECTION\nOF BEING THERE.'}</div><img className="sample-image" src={isCard?`/samples/${style}.png`:'/samples/album.png'} alt={isCard?'低电量城市漫游者，卡片排版示例':'周末出走计划，回忆册封面排版示例'}/><div className="sample-caption"><span className="small-dot"/>{isCard?'矛盾的状态，也可以刚刚好。':'那些舍不得扔的小纸片，都有了归处。'}</div></div>}
    <div className="preview-bottom"><span><Icon name="check" size={14}/> {isCard?'中文高清排版':'纸质手账排版'}</span><span><Icon name="check" size={14}/> 随时修改</span><span><Icon name="check" size={14}/> 下载珍藏</span></div>
   </section></div>}
   <footer className="footer"><span>{app.name} <span className="footer-divider">/</span> {isCard?'生活的每一面，都值得一版。':'为平凡日子，留一份底稿。'}</span><span>MADE FOR THE MOMENT · 2026</span>{session&&<span>今日创作 {session.used} / {session.limit}</span>}</footer>
  </main>
  {lightbox&&<div className="lightbox" role="dialog" aria-label="全屏预览" onClick={()=>setLightbox('')}><img src={lightbox} alt="作品全屏预览"/><button aria-label="关闭全屏预览" onClick={()=>setLightbox('')}>×</button></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
